#!/bin/bash

# This script runs latex compilation in a loop, using the fswatch command. Any time the file is modified (saved to, or simply "touch"ed, then this script will recompile 

FILE="$1"

if [[ -z "$FILE" ]]; then
    echo "ERROR: no filename specified"
    echo "usage: ./compile-loop <filename>"
    exit 1
fi

set -eu

if ! command -v fswatch &> /dev/null; then
    echo "the 'fswatch' was not found, please install before running"
fi

while true; do
    fswatch --one-event "$FILE" | sort -u | xargs -I{} bash -c './compile "{}" || true'
done
