#!/bin/bash
#
# Compile a specified latex document. This script creates an output
# directory and links all related compilation files into that directory
# so that the mess of latex intermediate files can be contained in
# their own directory. This script runs pdflatex and bibtex.
#

FILE="$1"

if [[ -z "$FILE" ]]; then
    echo "ERROR: no filename specified"
    echo "usage: ./compile <filename>"
    exit 1
fi

# fail on missing variables and any nonzero exit
set -euo pipefail

mkdir -p out

# link files required for compilation into the "out" dir
for glob in "*.bib" "figures/*.png" "figures/*.svg"; do
    if compgen -G "$glob" > /dev/null; then
        for f in $glob; do
            ln -frs "$f" out
        done
    fi
done

file_realpath="$(realpath "$FILE")"

# run compilation
cd out
pdflatex --shell-escape "$file_realpath"
bibtex $(basename "$file_realpath" .tex)
pdflatex --shell-escape "$file_realpath"
pdflatex --shell-escape "$file_realpath"
cp $(basename "$file_realpath" .tex).pdf ..
